[package]
name = "statemachine"
version = "0.1.0"
authors = ["imbolc <me@imbolc.name>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
statemachine-derive = { path = "statemachine-derive" }
rand = "0.8.5"
